import {createRequire} from 'node:module'; const require=createRequire(import.meta.url); const {FIELDS,colorValues}=require('../src/colors'); const defaults=colorValues({workspace:{getConfiguration:()=>({get:()=>({})})}},process.cwd(),'IKUN · 背带裤黑');
import {chromium} from 'playwright';import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';
const html=fs.readFileSync('media/club.html','utf8').replace('{{COLOR_ROWS}}',FIELDS.map(([id,label])=>`<label class="color-row"><span>${label}</span><input type="color" data-color="${id}" value="${defaults[id]}"><input class="hex" data-hex="${id}" value="${defaults[id]}" pattern="#[0-9A-Fa-f]{6}" required></label>`).join('')).replace(/\{\{(\w+)\}\}/g,(_,k)=>({CSP:"'self'",NONCE:'preview',CSS:'/media/club.css',JS:'/media/club.js',CHICKEN:'/icons/chicken.svg',FOLDER:'/icons/folder.svg',TS:'/icons/ts.svg',SHELL:'/icons/shell.svg',IMAGE:'/icons/image.svg',THEME:'IKUN · 背带裤黑',COLOR_HINT:'仅应用到当前这套配色。',DAILY:'true',LIGHT:'false',STAGE:'false'}[k]||''));
const server=http.createServer((req,res)=>{const p=req.url==='/'?null:req.url.slice(1);if(p&&!/^(media\/(club\.(js|css))|icons\/[a-z-]+\.svg)$/.test(p)){res.writeHead(404).end();return;}res.setHeader('Content-Type',p?.endsWith('css')?'text/css':p?.endsWith('js')?'text/javascript':p?.endsWith('svg')?'image/svg+xml':'text/html');res.end(p?fs.readFileSync(p):html);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.IKUN_CHROME||(fs.existsSync('/opt/google/chrome/chrome')?'/opt/google/chrome/chrome':undefined),headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:460,height:1150}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));assert.equal(await page.locator('details,audio').count(),0);assert.equal(await page.getByText('自己的梗').count(),0);assert.equal(await page.getByText('细节里，都是自己人。').count(),0);assert.equal(await page.getByText('本地运行',{exact:true}).count(),0);
await page.evaluate(()=>{window.sent=[];window.addEventListener('ikun-command',e=>window.sent.push(e.detail))});
for(const mode of ['daily','light','stage'])await page.locator(`[data-mode=${mode}]`).click();
for(const command of ['icons','restoreIcons','restoreFileIcons','restoreProductIcons','resetColors','advancedColors','restore'])await page.locator(`[data-command=${command}]`).click();
assert.deepEqual(await page.evaluate(()=>window.sent.map(m=>m.command)),['theme','theme','theme','icons','restoreIcons','restoreFileIcons','restoreProductIcons','resetColors','advancedColors','restore']);
await page.locator('[data-hex=background]').fill('#112233');
await page.locator('[data-hex=strings]').fill('invalid');
await page.locator('button[type=submit]').click();assert.equal(await page.evaluate(()=>window.sent.length),10);
await page.locator('[data-hex=strings]').fill('#aabbcc');await page.locator('button[type=submit]').click();
assert.deepEqual(await page.evaluate(()=>window.sent.at(-1)),{command:'saveColors',theme:'IKUN · 背带裤黑',colors:{background:'#112233',strings:'#AABBCC'}});
await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'result',ok:false,message:'应用失败'}})));assert.equal(await page.locator('#message').textContent(),'应用失败');await page.locator('#message').evaluate(el=>el.textContent='');await page.reload();await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await page.evaluate(()=>window.scrollTo(0,0));fs.mkdirSync('docs/previews',{recursive:true});await page.screenshot({path:'docs/previews/wardrobe.png',fullPage:true});for(const width of [220,280,360]){await page.setViewportSize({width,height:780});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow at ${width}`);}assert.deepEqual(errors,[]);
const icon=await browser.newPage({viewport:{width:128,height:128},deviceScaleFactor:1});await icon.setContent(`<style>body{margin:0;background:transparent}img{width:112px;height:112px;margin:8px}</style><img src="data:image/svg+xml;base64,${fs.readFileSync('icons/chicken.svg').toString('base64')}">`);await icon.locator('img').evaluate(i=>i.decode());await icon.screenshot({path:'media/icon.png',omitBackground:true});console.log('PASS: all preview icons, theme/icon controls, color payload and invalid HEX, errors, no removed media UI, 220–360px layout, no JS errors');}finally{await browser.close();server.close();}
